export enum UserTypes {
    SIGNUP_USER = "SIGNUP_USER",
    LOGIN_USER = "LOGIN_USER",
    SET_USER_DETAILS = "SET_USER_DETAILS",
    LOGOUT_USER = "LOG_OUT_USER",
    TRACE_CHANGES = "TRACE_CHANGES",
    UPDATE_PROFILE = "UPDATE_PROFILE",
    UPDATE_USER_CONTACTS = "UPDATE_USER_CONTACTS",
    UPADTE_INVOICE_FIELDS = "UPADTE_INVOICE_FIELDS",
    VERIFY_EMAIL = "VERIFY_EMAIL",
    SET_UKNOWN_CONTACTS = "SET_UKNOWN_CONTACTS",
    SET_EMAILS = "SET_EMAILS",
    SET_UNSEEN_EMAILS = "SET_UNSEEN_EMAILS",
    SET_EMAIL = "SET_EMAIL",
    REMOVE_EMAIL = "REMOVE_EMAIL",
    MARK_EMAIL_SEEN = "MARK_EMAIL_SEEN",
    SET_REPLY_EMAIL = "SET_REPLY_EMAIL",
    SEND_EMAIL = "SEND_EMAIL",
    SET_NOTIFICATIONS = "SET_NOTIFICATIONS",
    SET_NOTIFICATIONS_READ = "SET_NOTIFICATIONS_READ",
    LAST_CHAT_RECIPIENT = "LAST_CHAT_RECIPIENT",
}

export enum UITypes {
    SET_IS_EDIT = "SET_IS_EDIT",
    SET_IS_CONTACT = "SET_IS_CONTACT",
    SET_IS_PREVIEW = "SET_IS_PREVIEW",
    SET_IS_CHAT = "SET_IS_CHAT",
    SET_IS_ORDERS = "SET_IS_ORDERS",
    HANDLE_LOCK = "HANDLE_LOCK",
}

export enum DateTypes{
    SET_DATE = "SET_DATE"
}

export enum TodoTypes {
    IS_AVAILABLE_TRUE = "IS_AVAILABLE_TRUE",
    SET_TASKS = "SET_TASKS",
    TRACK_TASKS = "TRACK_TASKS",
    SET_COMPLETED = "SET_COMPLETED",
    SET_ORDER_FULLFILLED = "SET_ORDER_FULLFILLED",
    SET_ORDER_REJECTED = "SET_ORDER_REJECTED",
    SET_UNCOMPLETED = "SET_UNCOMPLETED",
    FILTER_ACTIVE = "FILTER_ACTIVE",
    FILTER_BY_DATE = "FILTER_BY_DATE",
    FILTER_COMPLETED = "FILTER_COMPLETED",
    FILTER_FULLFILLED = "FILTER_FULLFILLED",
    FILTER_REJECTED = "FILTER_REJECTED",
    FILTER_ALL = "FILTER_ALL",
    ADD_TASK = "ADD_TASK",
    EDIT_TASK = "EDIT_TASK",
    SAVE_TASK = "SAVE_TASK",
    REMOVE_TASK = "REMOVE_TASK",    
    REMOVE_ALL = "REMOVE_ALL",
    CHECK_IS_AVAIBLE = "CHECK_IS_AVAIBLE",
    SET_MONTHLY_ORDERS_AND_REJECTIONS = "SET_MONTHLY_ORDERS_AND_REJECTIONS",
    SET_YEARLY_BY_MONTH_REJECTIONS_AND_ORDERS = "SET_YEARLY_BY_MONTH_REJECTIONS_AND_ORDERS",
}


export enum InvoicesTypes{
    SET_FIELD = "SET_FIELD",
    SET_FIELDS = "SET_FIELDS",
    RESET_FIELDS = "RESET_FIELDS",
    SET_INVOICES = "SET_INVOICES",
    HANDLE_FORM_DATA = "HANDLE_FORM_DATA",
    ADD_INVOICE = "ADD_INVOICE",
    VIEW_INVOICE = "VIEW_INVOICE",
    REMOVE_INVOICE = 'REMOVE_INVOICE',
    TRACK_IVOICES = "TRACK_IVOICES",
    COUNT_MONEY_AND_UP = "COUNT_MONEY_AND_UP",
    COUNT_MONEY_YEARLY_BY_MONTH = "COUNT_MONEY_YEARLY_BY_MONTH",
}

export enum ContactsTypes{
    SET_CONTACTS = "SET_CONTACTS",
    ADD_CONTACT = "ADD_CONTACT"
}

export enum ChatTypes{
    SET_MESSAGES = "SET_MESSAGES",
    SEND_MESSAGE = "SEND_MESSAGE",
    FILTER_BY_EMAIL = "FILTER_BY_EMAIL",
    CHECK_READ = "CHECK_READ",
    MANAGE_MESSAGE = "MANAGE_MESSAGE",
    UPDATE_MESSAGES = "UPDATE_MESSAGES",
    UPDATE_CHAT_PROFILE_IMG = "UPDATE_CHAT_PROFILE_IMG",
}