export enum UITypes {
    SET_IS_EDIT = "SET_IS_EDIT"
}

export enum DateTypes{
    SET_DATE = "SET_DATE"
}

export enum CalendarTypes {
    SET_ACTIVE_EVENTS = "SET_ACTIVE_EVENTS"
}

export enum TodoTypes {
    IS_AVAILABLE_TRUE = "IS_AVAILABLE_TRUE",
    SET_TASKS = "SET_TASKS",
    SET_COMPLETED = "SET_COMPlETED",
    SET_UNCOMPLETED = "SET_UNCOMPLETED",
    FILTER_ACTIVE = "FILTER_ACTIVE",
    FILTER_BY_DATE = "FILTER_BY_DATE",
    FILTER_COMPLETED = "FILTER_COMPLETED",
    FILTER_ALL = "FILTER_ALL",
    ADD_TASK = "ADD_TASK",
    EDIT_TASK = "EDIT_TASK",
    SAVE_TASK = "SAVE_TASK",
    REMOVE_TASK = "REMOVE_TASK",    
    REMOVE_ALL = "REMOVE_ALL",
    CHECK_IS_AVAIBLE = "CHECK_IS_AVAIBLE"
}
