import React,{useState, useEffect } from 'react'
import Head from 'next/head'
import Spinner from './spinner.component'

interface LayoutProps{
  title:string,
  children:any
}

const Loader:React.FC<LayoutProps> = ({children,title}) => {
  const [loading,setLoading] = useState<boolean>(true)

  useEffect(()=>{
    setTimeout(()=>{
      setLoading(false)
    },2000)
  },[])

  return (
    <React.Fragment>
    {loading 
    ? <Spinner />
    : <div className="container">
      <Head>
        <title>DASH | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {children}
    </div>}
    </React.Fragment>
  )
}

export default Loader